# Generated by Django 5.1.1 on 2024-09-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("desc", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing"),
                            ("shoes", "Shoes"),
                            ("bags", "Bags"),
                            ("acc", "Accessories"),
                            ("others", "Others"),
                        ],
                        max_length=15,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("women", "Women"),
                            ("men", "Men"),
                            ("unisex", "Unisex"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
