# Generated by Django 5.1.1 on 2024-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_desc_product_description_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="conditions",
            field=models.CharField(default="no information", max_length=100),
        ),
    ]
